# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/cons/top/eth_tx_uart_rx_top_constrain.xdc

# XDC: C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/cons/top/eth_tx_uart_rx_top_constrain_time.xdc

# XDC: C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/cons/uart/uart_rx_io_constrain.xdc

# XDC: C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/cons/ethernet/ethernet_tx_io_constrain.xdc

# IP: C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/ip/ex_tx_uart_rx_fifo/ex_tx_uart_rx_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_tx_uart_rx_fifo || ORIG_REF_NAME==ex_tx_uart_rx_fifo} -quiet] -quiet

# IP: C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/ip/pll_25MHZ/pll_25MHZ.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pll_25MHZ || ORIG_REF_NAME==pll_25MHZ} -quiet] -quiet
