# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_eth_tx_uart_rx/video_trans_eth_tx_uart_rx.cache/wt} [current_project]
set_property parent.project_path {C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_eth_tx_uart_rx/video_trans_eth_tx_uart_rx.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.3 [current_project]
set_property ip_output_repo {c:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_eth_tx_uart_rx/video_trans_eth_tx_uart_rx.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/src/uart/rx/detect.v}
  {C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/src/ethernet/tx/ethernet_tx.v}
  {C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/src/uart/rx/rx_bps.v}
  {C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/src/uart/rx/rx_control.v}
  {C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/src/uart/rx/rx_uart.v}
  {C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/src/top/eth_tx_uart_rx.v}
}
read_ip -quiet {{C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/ip/ex_tx_uart_rx_fifo/ex_tx_uart_rx_fifo.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/ip/ex_tx_uart_rx_fifo/ex_tx_uart_rx_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/ip/ex_tx_uart_rx_fifo/ex_tx_uart_rx_fifo_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/ip/ex_tx_uart_rx_fifo/ex_tx_uart_rx_fifo_ooc.xdc}}]

read_ip -quiet {{C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/ip/pll_25MHZ/pll_25MHZ.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/ip/pll_25MHZ/pll_25MHZ_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/ip/pll_25MHZ/pll_25MHZ.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/ip/pll_25MHZ/pll_25MHZ_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/cons/top/eth_tx_uart_rx_top_constrain.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/cons/top/eth_tx_uart_rx_top_constrain.xdc}}]

read_xdc {{C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/cons/top/eth_tx_uart_rx_top_constrain_time.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/cons/top/eth_tx_uart_rx_top_constrain_time.xdc}}]

read_xdc {{C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/cons/uart/uart_rx_io_constrain.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/cons/uart/uart_rx_io_constrain.xdc}}]

read_xdc {{C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/cons/ethernet/ethernet_tx_io_constrain.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/KANG Jian/Desktop/video_trans_pro/video_trans_source/cons/ethernet/ethernet_tx_io_constrain.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top eth_tx_uart_rx -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef eth_tx_uart_rx.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file eth_tx_uart_rx_utilization_synth.rpt -pb eth_tx_uart_rx_utilization_synth.pb"
